# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.worldbank.com:
  peer0.xbank.worldbank.com:
  peer0.hdfc.worldbank.com:
  peer0.tatasteel.worldbank.com:
  peer0.lnt.worldbank.com:
  peer0.fedx.worldbank.com:
  peer0.sebi.worldbank.com:
  
networks:
  worldbank:

services:
  orderer.worldbank.com:
    container_name: orderer.worldbank.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      # - ORDERER_GENERAL_TLS_ENABLED=true
      # - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      # - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      # - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      # - ORDERER_KAFKA_VERBOSE=true
      # - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      # - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      # - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/worldbank.com/orderers/orderer.worldbank.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/worldbank.com/orderers/orderer.worldbank.com/tls/:/var/hyperledger/orderer/tls
        - orderer.worldbank.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - worldbank

  peer0.xbank.worldbank.com:
    container_name: peer0.xbank.worldbank.com

    networks:
      - worldbank
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_worldbank
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=120S
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=120S
      - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=120S
      - ORDERER_GENERAL_KEEPALIVE_SERVERTIMEOUT=120s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      - CORE_PEER_ID=peer0.xbank.worldbank.com
      - CORE_PEER_ADDRESS=peer0.xbank.worldbank.com:9001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9001
      - CORE_PEER_CHAINCODEADDRESS=peer0.xbank.worldbank.com:9002
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9002
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.xbank.worldbank.com:9001
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.xbank.worldbank.com:9001
      - CORE_PEER_LOCALMSPID=xbankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.xbank.worldbank.com:/var/hyperledger/production
    ports:
      - 9001:9001

  peer0.hdfc.worldbank.com:
    container_name: peer0.hdfc.worldbank.com
    networks:
      - worldbank
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_worldbank
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=120S
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=120S
      - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=120S
      - ORDERER_GENERAL_KEEPALIVE_SERVERTIMEOUT=120s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      - CORE_PEER_ID=peer0.hdfc.worldbank.com
      - CORE_PEER_ADDRESS=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9011
      - CORE_PEER_CHAINCODEADDRESS=peer0.hdfc.worldbank.com:9012
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9012
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_LOCALMSPID=hdfcMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hdfc.worldbank.com/peers/peer0.hdfc.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hdfc.worldbank.com/peers/peer0.hdfc.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hdfc.worldbank.com:/var/hyperledger/production
    ports:
      - 9011:9011


  peer0.tatasteel.worldbank.com:
    container_name: peer0.tatasteel.worldbank.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_worldbank
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=120S
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=120S
      - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=120S
      - ORDERER_GENERAL_KEEPALIVE_SERVERTIMEOUT=120s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      - CORE_PEER_ID=peer0.tatasteel.worldbank.com
      - CORE_PEER_ADDRESS=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9021
      - CORE_PEER_CHAINCODEADDRESS=peer0.tatasteel.worldbank.com:9022
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9022
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_LOCALMSPID=tatasteelMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/tatasteel.worldbank.com/peers/peer0.tatasteel.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/tatasteel.worldbank.com/peers/peer0.tatasteel.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.tatasteel.worldbank.com:/var/hyperledger/production
    ports:
      - 9021:9021
    networks:
      - worldbank

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.xbank.worldbank.com:9001
      - CORE_PEER_LOCALMSPID=xbankMSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/xbank.worldbank.com/users/Admin@xbank.worldbank.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.worldbank.com
      - peer0.xbank.worldbank.com
      - peer0.hdfc.worldbank.com
      - peer0.tatasteel.worldbank.com

    networks:
      - worldbank